# This file specifies the programming language used, the desired building and testing environment 
# Including dependencies which must be installed before the software can be built and tested, and various other parameters.
sudo: false
language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.12.5
